version: 2.1
executors:
  nodelts:
    docker:
      - image: cimg/node:lts      
jobs:
  build:
    executor: nodelts
    steps:
      - checkout
      - run: npm install && npm run build
  test:
    executor: nodelts
    steps:
      - run: npm run test

workflows:
  my-custom-workflow:
    jobs:
      - build
      - test